var DEFAULT_MAX_APP_COUNT = 3;
var SECURITY_CONTROLS_FORMAT = {
  FULL: 'full',
  SHORT: 'short',
  SHORT_WITH_BTN: 'shortWithBtn'
};
var ACCESS_POLICY_RESTRICTION = {
  SHARED_LINK: 'sharedLink',
  DOWNLOAD: 'download',
  EXTERNAL_COLLAB: 'externalCollab',
  APP: 'app',
  FTP: 'ftp'
};
var DOWNLOAD_CONTROL = {
  DESKTOP: 'desktop',
  FTP: 'ftp',
  MOBILE: 'mobile',
  WEB: 'web'
};
var LIST_ACCESS_LEVEL = {
  BLACKLIST: 'blacklist',
  BLOCK: 'block',
  WHITELIST: 'whitelist'
};
var MANAGED_USERS_ACCESS_LEVEL = {
  OWNERS_AND_COOWNERS: 'ownersCoOwners',
  OWNERS_COOWNERS_AND_EDITORS: 'ownersCoOwnersEditors'
};
var SHARED_LINK_ACCESS_LEVEL = {
  COLLAB_AND_COMPANY_ONLY: 'companyAndCollabOnly',
  COLLAB_ONLY: 'collabOnly',
  PUBLIC: 'public'
};
var APP_RESTRICTION_MESSAGE_TYPE = {
  DEFAULT: 'default',
  WITH_APP_LIST: 'withAppList',
  WITH_OVERFLOWN_APP_LIST: 'withOverflownAppList'
};
var CLASSIFICATION_COLOR_ID_0 = 0;
var CLASSIFICATION_COLOR_ID_1 = 1;
var CLASSIFICATION_COLOR_ID_2 = 2;
var CLASSIFICATION_COLOR_ID_3 = 3;
var CLASSIFICATION_COLOR_ID_4 = 4;
var CLASSIFICATION_COLOR_ID_5 = 5;
var CLASSIFICATION_COLOR_ID_6 = 6;
var CLASSIFICATION_COLOR_ID_7 = 7;
var DEFAULT_CLASSIFICATION_COLOR_ID = CLASSIFICATION_COLOR_ID_0;
export { ACCESS_POLICY_RESTRICTION, APP_RESTRICTION_MESSAGE_TYPE, CLASSIFICATION_COLOR_ID_0, CLASSIFICATION_COLOR_ID_1, CLASSIFICATION_COLOR_ID_2, CLASSIFICATION_COLOR_ID_3, CLASSIFICATION_COLOR_ID_4, CLASSIFICATION_COLOR_ID_5, CLASSIFICATION_COLOR_ID_6, CLASSIFICATION_COLOR_ID_7, DEFAULT_CLASSIFICATION_COLOR_ID, DEFAULT_MAX_APP_COUNT, DOWNLOAD_CONTROL, LIST_ACCESS_LEVEL, MANAGED_USERS_ACCESS_LEVEL, SECURITY_CONTROLS_FORMAT, SHARED_LINK_ACCESS_LEVEL };
//# sourceMappingURL=constants.js.map