var ITEM_TYPE_FILE = 'file';
var ITEM_TYPE_FOLDER = 'folder';
var ITEM_TYPE_WEBLINK = 'web_link';
var JSON_PATCH_OP_ADD = 'add';
var JSON_PATCH_OP_REMOVE = 'remove';
var JSON_PATCH_OP_REPLACE = 'replace';
var JSON_PATCH_OP_TEST = 'test';
var METADATA_FIELD_TYPE_ENUM = 'enum';
var METADATA_FIELD_TYPE_MULTISELECT = 'multiSelect';
export { ITEM_TYPE_FILE, ITEM_TYPE_FOLDER, ITEM_TYPE_WEBLINK, JSON_PATCH_OP_ADD, JSON_PATCH_OP_REMOVE, JSON_PATCH_OP_REPLACE, JSON_PATCH_OP_TEST, METADATA_FIELD_TYPE_ENUM, METADATA_FIELD_TYPE_MULTISELECT };
//# sourceMappingURL=constants.js.map