var GROWTH_382_EXPERIMENT_BUCKET = 'flyout';
var GROWTH_382_AUTOFLY_CLASS = 'presence-autofly';
var GROWTH_382_AUTOFLY_CLASS_FIRST_LOAD = 'presence-autofly-first-load';
export { GROWTH_382_EXPERIMENT_BUCKET, GROWTH_382_AUTOFLY_CLASS, GROWTH_382_AUTOFLY_CLASS_FIRST_LOAD };
//# sourceMappingURL=constants.js.map