export var FIELD_TYPE_DATE = 'date';
export var FIELD_TYPE_ENUM = 'enum';
export var FIELD_TYPE_INTEGER = 'integer';
export var FIELD_TYPE_FLOAT = 'float';
export var FIELD_TYPE_MULTISELECT = 'multiSelect';
export var FIELD_TYPE_STRING = 'string';
export var TEMPLATE_CUSTOM_PROPERTIES = 'properties';
export var JSON_PATCH_OP_ADD = 'add';
export var JSON_PATCH_OP_REMOVE = 'remove';
export var JSON_PATCH_OP_REPLACE = 'replace';
export var JSON_PATCH_OP_TEST = 'test';
//# sourceMappingURL=constants.js.map